### ISSUE TITLE
check up on isMultitenant

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#212]
We have the `isMultitenant` flag implemented long time ago, and should check if it still follows expected requirements:

scenario `isMultitenant=false`:
- should deploy only one prometheus-operator chart
- should not split logs in loki
- is all telemetry sent to that one prometheus endpoint?
- should hide any team apps in console
- are resources still segmented into their team-* namespaces?
- is authz checking for 'admin' or 'team-admin' role? it can disregard other roles

**Comment by j-zimnowoda** [comment]
1. We see that alert manager is not deployed when isMultitenant=false 
2. Team apps has incorrect links

**Comment by Morriz** [comment]
links are now fixed by @cocheok's PRs...is that observation about alertmanager correct @j-zimnowoda ? Is it truly not deploying? Are you talking about the one in ns `monitoring`?

**Comment by j-zimnowoda** [comment]
Links are not yet fixed as it needs otomi-console PR to be merged.
About alert manager I see the icon indicates that alert manager is enabled but it turns out that it is not deployed.  Perhaps otomi-console is not aware of the logic behind enabling alert manager `{{ if or ($v | get "alerts" false) ($v | get "home" false) }}`

**Comment by Morriz** [comment]
The links are fixed in the upcoming api+console PRs I am working on, so those are non issues when that lands...also, this is about core. If core is working correctly with this flag this ay be closed

**Comment by j-zimnowoda** [comment]
yea, about `alert manager` there is already an issue: #313

**Comment by j-zimnowoda** [comment]
obsoleted by redkubes/unassigned-issues#408
